### ISSUE TITLE
some small things

### ISSUE THREAD

**Issue by robdimsdale** [luan/vim-concourse#1]
- [x] known keyword in `params` should render as arbitrary key/value instead of keyword e.g.:
  https://github.com/robdimsdale/robdimsdale-ci/blob/master/concourse-pipeline-resource/pipeline.yml#L105
  - [x] same is true for `source` e.g. https://github.com/robdimsdale/robdimsdale-ci/blob/master/concourse-pipeline-resource/pipeline.yml#L38
- [x] colon in value should not cause half of the value to render as a key e.g.:
  https://github.com/robdimsdale/robdimsdale-ci/blob/master/concourse-pipeline-resource/pipeline.yml#L48
- [x] `get_params`, `do`, and `timeout` should be highlighted as a keywords. `do` and `timeout` seem to work when not directly under `plan`
- [x] `~` should render as yaml primitive (i.e. blue)
- [x] numbers are primitives are should be rendered as such (not rendered as strings)
- [x] `#` in strings should not cause the remainder of the string to render as comment

**Comment by robdimsdale** [comment]
Thanks for highlighting numbers as primitives. It looks like now some strings are being rendered as partial numbers, e.g. `4.0h` should be a string, but the 4 is rendering in blue

**Comment by luan** [comment]
fixed on 184ea3f, forgot to tag that one.
