### ISSUE TITLE
Disable automatic folding

### ISSUE THREAD

**Issue by gerhard** [luan/vim-concourse#3]
Would be great if there was a configuration option for this. I really don't like starting with the entire pipeline config folded.

**Comment by luan** [comment]
This is actually vim's default behavior, I bet if you open another filetype that has several folds defined by syntax you'll see something similar, that behavior is described [here](http://vim.wikia.com/wiki/All_folds_open_when_opening_a_file).
I could automatically **unfold** everything as part of this but I think that'd be surprising, I'll try to explore some options on that front though.

**Comment by gerhard** [comment]
This does the job, thanks!

``` vim
 " Disable all folds when opening Concourse files
au FileType concourse setlocal nofoldenable
```
