### ISSUE TITLE
Rainbow plugin dependency

### ISSUE THREAD

**Issue by gerhard** [luan/vim-concourse#4]
I couldn't start using this plugin without adding [luochen1990/rainbow](https://github.com/luochen1990/rainbow) to my vimrc. Either do not depend on it (my favourite) or define it as an explicit dependency.

**Comment by luan** [comment]
Fixed it here: 30afbe6d557f0b776ec6a5a33275d1c22020b8fe forgot to tag the commit. That was never supposed to be a dependency, haha, thanks for the issue!

**Comment by gerhard** [comment]
👍
